// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DeleteSystemVar(arg1) {
  return window['go']['main']['App']['DeleteSystemVar'](arg1);
}

export function DeleteUserVar(arg1) {
  return window['go']['main']['App']['DeleteUserVar'](arg1);
}

export function GetProcessEnvVars(arg1) {
  return window['go']['main']['App']['GetProcessEnvVars'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function ListProcesses() {
  return window['go']['main']['App']['ListProcesses']();
}

export function ListSystemVars() {
  return window['go']['main']['App']['ListSystemVars']();
}

export function ListUserVars() {
  return window['go']['main']['App']['ListUserVars']();
}

export function SetSystemVar(arg1, arg2) {
  return window['go']['main']['App']['SetSystemVar'](arg1, arg2);
}

export function SetUserVar(arg1, arg2) {
  return window['go']['main']['App']['SetUserVar'](arg1, arg2);
}
