// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteSystemVar(arg1:string):Promise<void>;

export function DeleteUserVar(arg1:string):Promise<void>;

export function GetProcessEnvVars(arg1:number):Promise<Array<model.EnvVar>>;

export function KillProcess(arg1:number):Promise<void>;

export function ListProcesses():Promise<Array<model.ProcessInfo>>;

export function ListSystemVars():Promise<Array<model.EnvVar>>;

export function ListUserVars():Promise<Array<model.EnvVar>>;

export function SetSystemVar(arg1:string,arg2:string):Promise<void>;

export function SetUserVar(arg1:string,arg2:string):Promise<void>;
